/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_pigler_api_PiglerAPI */

#ifndef _Included_org_pigler_api_PiglerAPI
#define _Included_org_pigler_api_PiglerAPI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_pigler_api_PiglerAPI
 * Method:    _createEventSource
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_pigler_api_PiglerAPI__1createEventSource
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_pigler_api_PiglerAPI
 * Method:    _createAPI
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_pigler_api_PiglerAPI__1createAPI
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_pigler_api_PiglerAPI
 * Method:    _dispose
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_pigler_api_PiglerAPI__1dispose
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_pigler_api_PiglerAPI
 * Method:    _initRandom
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_org_pigler_api_PiglerAPI__1initRandom
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_pigler_api_PiglerAPI
 * Method:    _init
 * Signature: (IIILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_pigler_api_PiglerAPI__1init
  (JNIEnv *, jobject, jint, jint, jint, jstring);

/*
 * Class:     org_pigler_api_PiglerAPI
 * Method:    _setNotification
 * Signature: (IIILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_pigler_api_PiglerAPI__1setNotification
  (JNIEnv *, jobject, jint, jint, jint, jstring);

/*
 * Class:     org_pigler_api_PiglerAPI
 * Method:    _removeNotification
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_org_pigler_api_PiglerAPI__1removeNotification
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_pigler_api_PiglerAPI
 * Method:    _removeAllNotifications
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_pigler_api_PiglerAPI__1removeAllNotifications
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_pigler_api_PiglerAPI
 * Method:    _getLastTappedNotification
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_pigler_api_PiglerAPI__1getLastTappedNotification
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_pigler_api_PiglerAPI
 * Method:    _setRemoveNotificationOnTap
 * Signature: (IIIZ)I
 */
JNIEXPORT jint JNICALL Java_org_pigler_api_PiglerAPI__1setRemoveNotificationOnTap
  (JNIEnv *, jobject, jint, jint, jint, jboolean);

/*
 * Class:     org_pigler_api_PiglerAPI
 * Method:    _setNotificationIcon
 * Signature: (III[I)I
 */
JNIEXPORT jint JNICALL Java_org_pigler_api_PiglerAPI__1setNotificationIcon
  (JNIEnv *, jobject, jint, jint, jint, jintArray);

/*
 * Class:     org_pigler_api_PiglerAPI
 * Method:    _close
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_pigler_api_PiglerAPI__1close
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_pigler_api_PiglerAPI
 * Method:    _getAPIVersion
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_pigler_api_PiglerAPI__1getAPIVersion
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_pigler_api_PiglerAPI
 * Method:    _setLaunchAppOnTap
 * Signature: (IIIZ)I
 */
JNIEXPORT jint JNICALL Java_org_pigler_api_PiglerAPI__1setLaunchAppOnTap
  (JNIEnv *, jobject, jint, jint, jint, jboolean);

/*
 * Class:     org_pigler_api_PiglerAPI
 * Method:    _getNotificationsCount
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_pigler_api_PiglerAPI__1getNotificationsCount
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_pigler_api_PiglerAPI
 * Method:    _getMaxNotificationsCount
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_pigler_api_PiglerAPI__1getMaxNotificationsCount
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
